### PR TITLE
ENH update to cbd3

### PR DESCRIPTION
**Pull request by beckermr**
This PR closes #5 and closes #6 and closes #8

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
OK @mariusvniekerk @slinderman @conda-forge/pypolyagamma, as far as i can tell, this rebuild is blocked on issues

https://github.com/slinderman/pypolyagamma/issues/26
https://github.com/slinderman/pypolyagamma/issues/27

The pypi distribution doesn't seem to be up to date with the repo and tags are missing. 

For python 3.7, cython needs to be rerun and the current files in the pypi distribution barf due to not having the pxd header stuff.

**Comment by slinderman** [comment]
Hi Matthew, 

Thanks for your effort to ease the pypolyagamma install process.  Getting this to work reliably across platforms has been a pain from the beginning.  The hard part is that the underlying C code for sampling Polya-gamma random variables requires GSL, and asking users to install GSL and set up their library path appropriately was not working.  I ended up taking a hacky approach of downloading GSL during the install procedure and directly including the necessary headers and source files when compiling PyPolyaGamma.  

Life could be a lot easier now that conda includes GSL and OpenMP for all platforms.  I started a branch https://github.com/slinderman/pypolyagamma/tree/condagsl that strips out the GSL download stuff and just assumes that `gsl` and `gslcblas` libraries are available.   If we're going to create a conda package for pypolyagamma, we should require these dependencies and assume they are available during installation.  Is that possible?

Best,
Scott

**Comment by slinderman** [comment]
Let me also add that conda would be my preferred method of shipping this code, if it can automatically handle the GSL and OpenMP dependencies across platforms.  Ideally, `conda install pypolyagamma` would:
1. install GSL and OpenMP, if necessary
2. clone pypolyagamma from github (rather than from pypi)
3. cythonize and compile the pypolyagamma source (should work now that all dependencies are taken care of)
4. pip install the package

If that is possible, that would eliminate the need for hosting this on pypi and make life easier for everyone.

**Comment by beckermr** [comment]
Thanks for the note!

The vendored gsl is not the issue here. We can definitely fix that.

However  right now the cython code on pypi generates errors when cythonizing the code. This has to be fixed before we can do anything else. 

Also the way conda works is that it builds binaries for each platform as opposed to building the binaries on installation. It is setup very carefully to make this process robust. 

Let’s fix the cython issues and then we can address the gsl stuff!

Fixing this requires us to add tags to the upstream repo and update the pypi distribution per the issues I made above.

**Comment by beckermr** [comment]
Alright. Let's see if this builds OK. If not, I will fix the build errors tonight.

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
OK @slinderman. Press merge and this rebuild is done!

**Comment by slinderman** [comment]
Minor problem... I don't have write access to this repo!

**Comment by beckermr** [comment]
lol you are on the list of maintainers - The other maintainer no longer exists according the linter. I guess we need @conda-forge/core to rescue us!

Hi core! 

Neither of us have commit access to this feedstock and the [team](https://github.com/orgs/conda-forge/teams/pypolyagamma/members) is empty! 

Can you help us adopt this orphaned feedstock?

I think if you press merge the admin will add us to the team!

**Comment by isuruf** [comment]
@slinderman, go to https://github.com/orgs/conda-forge/invitation for your invitation.

**Comment by slinderman** [comment]
Thanks @isuruf.  I must have missed the invitation email long ago.  I've joined and merged the PR.

**Pull request merged**
